### PR TITLE
Joomla 3 2

### PR DESCRIPTION
**Pull request by MichaelEntov**
Dear Tobias, 

Would you be able to update your wonderful Titlelink plugin for Joomla so that it works with PHP 8 and Joomla 4? At the moment it does not work with PHP 8 ("Uncaught Throwable of type TypeError thrown") and doesn't pass Joomla 4 preinstallation check. It seems that the issue is as described here:

https://php.watch/versions/8.0/internal-function-exceptions

Below is an error log that I get when I try to upgrade to PHP 8 - I don't know if it helps.

Best regards and many thanks for your help,
Michael

-------------------------

CRITICAL 
::1	error	Uncaught Throwable of type TypeError thrown. 
Stack trace: #0 [ROOT]\plugins\system\titlelink\titlelink.php(315): plgSystemTitleLink->getByPlugins(Object(JDatabaseDriverMysqli), Array, '\xD7\x9B\xD7\x9C\xD7\x9C\xD7\x99 \xD7\xA9\xD7\x99\xD7\x9E...', false)
#1 [ROOT]\plugins\system\titlelink\titlelink.php(118): plgSystemTitleLink->replaceTitleLinksWithURLs('<!DOCTYPE html>...')
#2 [ROOT]\libraries\joomla\event\event.php(70): plgSystemTitleLink->onAfterRender()
#3 [ROOT]\libraries\joomla\event\dispatcher.php(160): JEvent->update(Array)
#4 [ROOT]\libraries\src\Application\BaseApplication.php(108): JEventDispatcher->trigger('onafterrender', Array)
#5 [ROOT]\libraries\src\Application\CMSApplication.php(1118): Joomla\CMS\Application\BaseApplication->triggerEvent('onAfterRender')
#6 [ROOT]\libraries\src\Application\SiteApplication.php(778): Joomla\CMS\Application\CMSApplication->render()
#7 [ROOT]\libraries\src\Application\CMSApplication.php(231): Joomla\CMS\Application\SiteApplication->render()
#8 [ROOT]\index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#9 {main}

### CODE REVIEW

**Comment by hmueller01** [comment]
I do not use J4, still on J3.10.11 but using PHP 8.0/8.1 and using the latest titlelink https://github.com/gesellix-joomla/titlelink works for me ...

**Comment by MichaelEntov** [comment]
> I do not use J4, still on J3.10.11 but using PHP 8.0/8.1 and using the latest titlelink https://github.com/gesellix-joomla/titlelink works for me ...

Thanks.

What extensions and options in PHP 8.1 are you using?

**Comment by MichaelEntov** [comment]
> I do not use J4, still on J3.10.11 but using PHP 8.0/8.1 and using the latest titlelink https://github.com/gesellix-joomla/titlelink works for me ...

Reinstalled the package "titlelink-develop.zip" - and it does work with PHP 8.1! Many thanks!!!

**Comment by hmueller01** [comment]
Perfect. Do you see version 3.7.0 2018-12-01 in your Extensions: Manage view?
I asked Tobias #19 to merge his fork here. Hope he does it soon, than this PR can be closed.

**Comment by MichaelEntov** [comment]
> Perfect. Do you see version 3.7.0 2018-12-01 in your Extensions: Manage view? I asked Tobias #19 to merge his fork here. Hope he does it soon, than this PR can be closed.

Yes, I see it in my Extensions: Manage view - thanks!

If you guys could make more clear that this package is the latest version and add it to
https://github.com/gesellix-joomla/titlelink/tree/develop/packages
it would be helpful - the other packages there just did not install at all...

**Comment by gesellix** [comment]
Hey, sorry for the confusion (my bad to start with that fork and also to not cleaning up). I'm going to consolidate everything soonish. Also regarding the modern approach with GitHub releases or packages: I'll follow your suggestion to use those for publishing binaries or installable packages.

That said: do I understand correctly that everything works fine with a combination of a recent PHP version and Joomla 3.x? In other words: I would have to focus on the migration to Joomla 4.x?

**Comment by MichaelEntov** [comment]
> Hey, sorry for the confusion (my bad to start with that fork and also to not cleaning up). I'm going to consolidate everything soonish. Also regarding the modern approach with GitHub releases or packages: I'll follow your suggestion to use those for publishing binaries or installable packages.
> 
> That said: do I understand correctly that everything works fine with a combination of a recent PHP version and Joomla 3.x? In other words: I would have to focus on the migration to Joomla 4.x?

Thanks! As far as I am concerned, the recent Titlelink version works fine with the current version of Joomla 3.x and PHP 8.1. I have not tried it with Joomla 4.x yet but I do see that the Joomla 4.x preinstallation check still shows that there is a potential issue with Titlelink.

**Comment by MichaelEntov** [comment]
> > Hey, sorry for the confusion (my bad to start with that fork and also to not cleaning up). I'm going to consolidate everything soonish. Also regarding the modern approach with GitHub releases or packages: I'll follow your suggestion to use those for publishing binaries or installable packages.
> > That said: do I understand correctly that everything works fine with a combination of a recent PHP version and Joomla 3.x? In other words: I would have to focus on the migration to Joomla 4.x?
> 
> Thanks! As far as I am concerned, the recent Titlelink version works fine with the current version of Joomla 3.x and PHP 8.1. I have not tried it with Joomla 4.x yet but I do see that the Joomla 4.x preinstallation check still shows that there is a potential issue with Titlelink.

I am sorry, my previous happy conclusion that Titlelink works with Joomla 3.X and PHP 8.1 seems to have been premature. When I open certain (but not all) menus, I get the following error which I did not get before installing the updated version of Titlelink and upgrading to PHP 8.1:

count(): Argument #1 ($value) must be of type Countable|array, null given - 0

Debugging information shows:

JROOT/plugins/system/titlelink/titlelink.php:295 
JROOT/plugins/system/titlelink/titlelink.php:120 plgSystemTitleLink->replaceTitleLinksWithURLs()
JROOT/libraries/joomla/event/event.php:70 plgSystemTitleLink->onAfterRender()

It looks like the problem is caused by Titlelink interacting with PHP 8.1...

Could you, guys, help?

**Comment by MichaelEntov** [comment]
When I downgrade to PHP 7.4 the above problem disappears.

**Comment by hmueller01** [comment]
This new version of count sucks. It's easily fixable by replacing line 295:

 `                           if (count($result) != 2) && ($partial_match)) {`
by
`                             if ($result == null || ((count($result) != 2) && ($partial_match))) {`

and also line 305
 `                       if (count($result) == 2) {`
by
`                        if ($result != null && count($result) == 2) {
`
Atfer Tobias merged his branch into this master I can make a PR ...

**Comment by gesellix** [comment]
@hmueller01 @MichaelEntov I created https://github.com/gesellix/titlelink/pull/20, could any of you try the changed code and leave some feedback in that pull request? Thanks you!

**Comment by MichaelEntov** [comment]
Dear Tobias,

Many thanks!

Sorry for the ignorance: where can I find the updated Titlelink package
(with your latest corrections) that I can install?

Best,
Michael

**Comment by gesellix** [comment]
@MichaelEntov sorry, I assumed you would install it from the sources. I'm going to create a package and leave a link here. Stay tuned! :)

**Comment by gesellix** [comment]
Please head over to https://github.com/gesellix/titlelink/pull/20#issuecomment-1287890436 for the package and further discussion. Thanks for your quick reaction :)

**Comment by MichaelEntov** [comment]
Dear Tobias and Holger,

I have tried to upgrade to Joomla 4.2.5 (with PHP 8.1) and to install the latest version of Titlelink there (see above in this thread) and I have got the following error:

# | Function | Location
1 | () | JROOT\plugins\system\titlelink\titlelink.php:108
2 | plgSystemTitleLink->onAfterRender() | JROOT\libraries\src\Plugin\CMSPlugin.php:279
3 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
4 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:107
5 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\libraries\src\Application\CMSApplication.php:1023
6 | Joomla\CMS\Application\CMSApplication->render() | JROOT\libraries\src\Application\AdministratorApplication.php:417
7 | Joomla\CMS\Application\AdministratorApplication->render() | JROOT\libraries\src\Application\CMSApplication.php:299
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:61
9 | require_once() | JROOT\administrator\index.php:32

Could you please help?

Thanks and best regards,
Michael Entov

**Comment by hmueller01** [comment]
I am sorry but I can't help you on that. I have no Joomla 4 installation. Maybe @gesellix got one ...

**Comment by MichaelEntov** [comment]
@gesellix, can you help with the problem above? Thanks a lot in advance!

**Pull request merged**
